version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/concept-exporter
    docker:
      - image: golang:1.8.3
        environment:
          GOPATH: /go
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
    steps:
      - setup_docker_engine:
          docker_layer_caching: true
      - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.12.1-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
      - checkout
      - run:
          name: External Dependencies
          command: |
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
            go get -u github.com/kardianos/govendor
            go get -u github.com/haya14busa/goverage
            docker pull mongo:3.0.2
            docker run -d -P mongo:3.0.2
      - run:
          name: Test Results
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}
            mkdir -p ${CIRCLE_COVERAGE_REPORT}
      - run:
          name: Govendor Sync
          command: govendor sync -v
      - run:
          name: Go Build
          command: go build -v
      - run:
          name: Run Tests
          command: |
            export MONGO_TEST_URL=$(docker port $(docker ps | grep mongo | awk '{print $1}') 27017);
            govendor test -race -v +local | /go/bin/go-junit-report > ${CIRCLE_TEST_REPORTS}/main.xml
            export MONGO_TEST_URL=$(docker port $(docker ps | grep mongo | awk '{print $1}') 27017);
            goverage -covermode=atomic -race -coverprofile=${CIRCLE_COVERAGE_REPORT}/coverage.out ./...
      - run:
          name: Upload Coverage
          command: /go/bin/goveralls -coverprofile=${CIRCLE_COVERAGE_REPORT}/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-results
  dockerfile:
    working_directory: /concept-exporter
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
