# Values used for the deployed application.
service:
  name: content-exporter
env:
  kafka:
    groupId: "content-exporter"
  s3Writer:
    baseUrl: "http://upp-exports-rw-s3:8080"
  contentOriginAllowlist: "^http://upp-content-validator\\.svc\\.ft\\.com(:\\d{2,5})?/content/[\\w-]+.*$"
  allowedContentTypes: "Article"
