# Default values for content-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  serviceAccountName: eksctl-content-exporter-serviceaccount
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/content-exporter
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 40Mi
  limits:
    memory: 256Mi
openPolicyAgentSidecar:
  name: open-policy-agent
  repository: openpolicyagent/opa
  tag: 0.58.0
  pullPolicy: IfNotPresent
env:
  db:
    database: "upp-store"
    collection: "content"
    timeout: 60
  kafka:
    groupId: "content-exporter"
    topic: "PostPublicationEvents"
  s3Writer:
    baseUrl: "http://upp-exports-rw-s3:8080"
    apiPath: "content"
  contentOriginAllowlist: "^http://upp-content-validator\\.svc\\.ft\\.com(:\\d{2,5})?/content/[\\w-]+.*$"
  allowedContentTypes: "Article"
  allowedPublishUUIDs: "88fdde6c-2aa4-4f78-af02-9f680097cfd6"
  enrichedContent:
    baseUrl: "http://api-policy-component:8080"
    apiPath: "enrichedcontent"
  contentRetrievalThrottle: 500
