# Default values for content-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/content-exporter
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 40Mi
  limits:
    memory: 256Mi
env:
  enrichedContent:
    baseUrl: "api-policy-component:8080"
    healthUrl: "api-policy-component:8080/__gtg"
  s3Writer:
    baseUrl: "upp-exports-rw-s3:8080"
    healthUrl: "upp-exports-rw-s3:8080/__gtg"
  kafka:
    groupId: "k8s-content-exporter"
    topic: "PostPublicationEvents"
  whitelist: "^http://(methode|wordpress)-article-(transformer|mapper)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content)/[\\w-]+.*$"